spring.application.name=gerenciamento-departamento

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Console H2 (acessível em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar SQL no console (opcional, ajuda a debugar)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update